# Generated by Django 5.2.6 on 2025-09-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_id",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Телеграм Chat ID"),
        ),
    ]
