# Generated by Django 5.2.6 on 2025-09-25 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habit_periodicity_alter_habit_time_to_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(max_length=255, verbose_name="Действие"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="associated_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="is_enjoyable",
            field=models.BooleanField(default=False, verbose_name="Признак приятной привычки"),
        ),
        migrations.DeleteModel(
            name="Action",
        ),
    ]
